[mypy]
mypy_path = .
namespace_packages = True
explicit_package_bases = True
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
strict_equality = True
warn_unreachable = True
check_untyped_defs = True
show_error_codes = True
color_output = True
extra_checks = True

# Ignore missing imports for third-party libraries
[mypy-stringzilla]
ignore_missing_imports = True

[mypy-jaconv]
ignore_missing_imports = True

[mypy-pyperclip]
ignore_missing_imports = True

[mypy-watchdog.*]
ignore_missing_imports = True
