[tool.polylith]
namespace = "text_processing"
git_tag_pattern = "stable-*"

[tool.polylith.structure]
theme = "loose"

[tool.polylith.tag.patterns]
stable = "stable-*"
release = "v[0-9]*"

[tool.polylith.resources]
brick_docs_enabled = true  # ブリックドキュメント有効化

[tool.polylith.test]
enabled = true
